"""Build drawing_index.json for the CP-129 PDF source set.

This scanner keeps the renamed PDF filenames intact and creates a small lookup
index for the Type overview UI.
"""
from __future__ import annotations

import argparse
import json
import re
from datetime import datetime, timezone
from pathlib import Path


APP_DIR = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE_DIR = APP_DIR / "assets" / "Type_cp129_2026"
DEFAULT_OUTPUT = APP_DIR / "configs" / "drawing_index.json"

TYPE_DRAWING_RE = re.compile(
    r"^TYPE-(?P<type_id>[A-Za-z0-9]+)_D-(?P<drawing>[A-Za-z0-9.-]+)\.pdf$",
    re.IGNORECASE,
)
M_SERIES_RE = re.compile(
    r"^(?P<prefix>TYPE-[^_]+|UnknownType)_M-(?P<m_id>[A-Za-z0-9.-]+)\.pdf$",
    re.IGNORECASE,
)


def _natural_key(value: str) -> list[object]:
    parts = re.split(r"(\d+)", value.upper())
    return [int(part) if part.isdigit() else part for part in parts]


def _normalize_type_id(value: str) -> str:
    text = value.upper()
    match = re.fullmatch(r"0*(\d+)([A-Z]*)", text)
    if match:
        number, suffix = match.groups()
        return f"{int(number):02d}{suffix}" if int(number) < 100 else f"{int(number)}{suffix}"
    return text


def _normalize_m_id(value: str) -> str:
    text = value.upper()
    if text.startswith("M-"):
        return text
    return f"M-{text}"


def _record(
    *,
    pdf: str,
    drawing: str,
    source_kind: str,
    source_label: str,
) -> dict:
    return {
        "pdf": pdf,
        "drawing": drawing,
        "source_kind": source_kind,
        "source_label": source_label,
    }


def scan_source(source_dir: Path) -> dict:
    grouped: dict[str, list[dict]] = {}
    unmatched: list[str] = []

    for path in sorted(source_dir.glob("*.pdf"), key=lambda p: _natural_key(p.name)):
        name = path.name
        type_match = TYPE_DRAWING_RE.fullmatch(name)
        if type_match:
            type_id = _normalize_type_id(type_match.group("type_id"))
            drawing = f"D-{type_match.group('drawing').upper()}"
            grouped.setdefault(type_id, []).append(
                _record(
                    pdf=name,
                    drawing=drawing,
                    source_kind="type",
                    source_label=f"TYPE-{type_id}",
                )
            )
            continue

        m_match = M_SERIES_RE.fullmatch(name)
        if m_match:
            type_id = _normalize_m_id(m_match.group("m_id"))
            grouped.setdefault(type_id, []).append(
                _record(
                    pdf=name,
                    drawing=type_id,
                    source_kind="component",
                    source_label=m_match.group("prefix"),
                )
            )
            continue

        unmatched.append(name)

    types: dict[str, dict] = {}
    for type_id, records in sorted(grouped.items(), key=lambda item: _natural_key(item[0])):
        records = sorted(records, key=lambda item: _natural_key(item["pdf"]))
        types[type_id] = {
            "primary_pdf": records[0]["pdf"],
            "pdfs": [item["pdf"] for item in records],
            "drawings": [item["drawing"] for item in records],
            "records": records,
        }

    return {
        "schema_version": 1,
        "source_set": "CP-129 2026 update",
        "source_dir": "assets/Type_cp129_2026",
        "generated_at": datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds"),
        "notes": [
            "Generated by python_app/tools/build_drawing_index.py.",
            "Keep PDF filenames unchanged; this file maps them to Type/M IDs.",
            "Type overview uses this index before falling back to legacy assets/Type PDFs.",
        ],
        "types": types,
        "unmatched_files": unmatched,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE_DIR)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    source = args.source.resolve()
    if not source.exists():
        raise SystemExit(f"Source directory does not exist: {source}")

    index = scan_source(source)
    type_count = len(index["types"])
    pdf_count = sum(len(item["pdfs"]) for item in index["types"].values())
    unmatched_count = len(index["unmatched_files"])
    print(f"Scanned: {source}")
    print(f"Indexed IDs: {type_count}")
    print(f"Indexed PDFs: {pdf_count}")
    print(f"Unmatched PDFs: {unmatched_count}")

    if args.dry_run:
        preview = list(index["types"].items())[:10]
        for type_id, record in preview:
            print(f"  {type_id}: {', '.join(record['pdfs'])}")
        return 0

    output = args.output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        json.dumps(index, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"Wrote: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
